name: Tutorials

on:
  push:
    branches: [main, release]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron:  '2 3 * * 4'


jobs:
  Tutorials:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
      - name: Install MacOS dependencies
        run: |
            brew install libomp
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Install dependencies
        run: |
            pip install --upgrade pip
            pip install -r requirements.txt
            python -m pip install ipykernel
            python -m ipykernel install --user
      - name: Run the tutorial 1
        run:  python tests/nb_eval.py --nb Tutorials/Case\ Study\ 1\ -\ Data\ Modality.ipynb
      - name: Run the tutorial 2
        run:  python tests/nb_eval.py --nb Tutorials/Case\ Study\ 2\ -\ Fairness.ipynb 
      - name: Run the tutorial 3
        run:  python tests/nb_eval.py --nb Tutorials/Case\ Study\ 3\ -\ Privacy.ipynb 
      - name: Run the tutorial 4
        run:  python tests/nb_eval.py --nb Tutorials/Case\ Study\ 4\ -\ Augmentation\ by\ Domain\ Adaptation.ipynb 